---
type: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    repo: jonnrb/etcdhcp
    username:
      from_secret: docker_username

- name: trigger
  image: plugins/downstream
  settings:
    fork: true
    repositories:
    - jon/wifi_dash
    server: https://drone.jonnrb.com
    token:
      from_secret: drone_token

- name: notify-slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  when:
    status:
    - success
    - failure

...
